import React, { useEffect, useMemo, useState } from 'react';
import { MapContainer, Marker, Polyline, Popup, TileLayer, Tooltip, useMap } from 'react-leaflet';
import L from 'leaflet';
import { AlertTriangle, BrainCircuit, CloudRain, RefreshCw, Route, Truck } from 'lucide-react';
import { api } from '../../services/api';
import { Corridor, Incident, RoadRiskPredictionResponse, RouteOption, Segment, Vehicle, WeatherData } from '../../types';

interface LiveMapProps { corridors: Corridor[]; vehicles: Vehicle[]; incidents: Incident[]; weather: WeatherData[]; selectedRoute: RouteOption | null; segments?: Segment[]; onMapClickCoordinates?: (lat: number, lng: number) => void; onUpvoteIncident?: (id: string) => void; onVerifyIncident?: (id: string) => void; onTriggerDisruption?: (id: string, type: 'landslide' | 'flood' | 'blocked-road') => void; onTriggerDelay?: (id: string, minutes: number) => void; compact?: boolean; onRefresh?: () => void; }
const center: [number, number] = [25.82, 92.38];
const color = (risk?: string, supplied?: string) => supplied?.startsWith('#') ? supplied : ['SAFE', 'LOW'].includes((risk || '').toUpperCase()) ? '#16a34a' : ['MEDIUM', 'MODERATE', 'CAUTION'].includes((risk || '').toUpperCase()) ? '#d97706' : '#dc2626';
const vehicleIcon = (v: Vehicle) => L.divIcon({ className: 'map-marker', iconSize: [34, 34], iconAnchor: [17, 17], html: `<span class="marker-dot marker-vehicle" style="transform:rotate(${v.heading_deg || 0}deg)">➤</span>` });
const incidentIcon = (i: Incident) => L.divIcon({ className: 'map-marker', iconSize: [30, 30], iconAnchor: [15, 15], html: `<span class="marker-dot ${i.severity === 'CRITICAL_CUTOFF' ? 'marker-critical' : 'marker-incident'}">!</span>` });
function MapHelper({ focus, onClick }: { focus: [number, number] | null; onClick?: (lat: number, lng: number) => void }) { const map = useMap(); useEffect(() => { const id = setTimeout(() => map.invalidateSize(), 100); return () => clearTimeout(id); }, [map]); useEffect(() => { if (focus) map.flyTo(focus, 9, { duration: .7 }); }, [focus, map]); useEffect(() => { if (!onClick) return; const fn = (e: L.LeafletMouseEvent) => onClick(+e.latlng.lat.toFixed(4), +e.latlng.lng.toFixed(4)); map.on('click', fn); return () => { map.off('click', fn); }; }, [map, onClick]); return null; }

export const LiveMap: React.FC<LiveMapProps> = ({ corridors, vehicles, incidents, weather, selectedRoute, segments: passed, onMapClickCoordinates, onUpvoteIncident, onVerifyIncident, compact, onRefresh }) => {
  const [segments, setSegments] = useState<Segment[]>(passed || []); const [vehiclesVisible, setVehiclesVisible] = useState(true); const [incidentsVisible, setIncidentsVisible] = useState(true); const [weatherVisible, setWeatherVisible] = useState(false); const [selectedId, setSelectedId] = useState(''); const [prediction, setPrediction] = useState<RoadRiskPredictionResponse | null>(null); const [error, setError] = useState(''); const [predicting, setPredicting] = useState(false); const [focus, setFocus] = useState<[number, number] | null>(null);
  useEffect(() => { if (passed?.length) setSegments(passed); }, [passed]); useEffect(() => { if (!passed?.length) api.getSegments().then(setSegments).catch(() => setSegments([])); }, [passed]);
  const active = useMemo(() => segments.find((segment) => segment.id === selectedId), [segments, selectedId]);
  const predict = async () => { if (!active) return; setPredicting(true); setError(''); try { const result = await api.predictRoadRisk({ segment_id: active.id, rainfall_mm: active.rainfall_mm ?? 50, landslide_history: active.landslide_history ?? 0, road_condition: active.road_condition ?? 'Fair' }); setPrediction(result); setSegments((items) => items.map((item) => item.id === active.id ? { ...item, risk_level: result.risk_level, risk_score: result.risk_score, color: result.color, alternate_route_polyline: result.alternate_route?.waypoints || item.alternate_route_polyline } : item)); } catch { setError('Risk prediction is currently unavailable.'); } finally { setPredicting(false); } };
  return <div className={`map-shell ${compact ? 'map-shell-compact' : ''}`}>
    <div className="map-toolbar"><button className="map-control active" onClick={() => setVehiclesVisible(!vehiclesVisible)}><Truck size={14} /> Vehicles {vehicles.length}</button><button className={`map-control ${incidentsVisible ? 'active-danger' : ''}`} onClick={() => setIncidentsVisible(!incidentsVisible)}><AlertTriangle size={14} /> Incidents {incidents.length}</button><button className={`map-control ${weatherVisible ? 'active' : ''}`} onClick={() => setWeatherVisible(!weatherVisible)}><CloudRain size={14} /> Weather</button>{!compact && <select value={selectedId} aria-label="Select road segment" onChange={(event) => { setSelectedId(event.target.value); const segment = segments.find((item) => item.id === event.target.value); if (segment) setFocus([segment.start_lat, segment.start_lng]); }}><option value="">Select road segment</option>{segments.map((segment) => <option key={segment.id} value={segment.id}>{segment.start_point_name} - {segment.end_point_name}</option>)}</select>}{onRefresh && <button className="map-control" aria-label="Refresh data" onClick={onRefresh}><RefreshCw size={14} /></button>}</div>
    {!compact && active && <aside className="risk-panel"><div className="panel-kicker"><BrainCircuit size={14} /> AI road intelligence</div><strong>{active.start_point_name} - {active.end_point_name}</strong><p>Risk score: {Math.round(active.risk_score || 0)} · {active.status}</p><button className="primary-button" onClick={predict} disabled={predicting}>{predicting ? 'Analysing...' : 'Run risk analysis'}</button>{prediction && <div className="prediction-result"><b style={{ color: color(prediction.risk_level, prediction.color) }}>{prediction.risk_level} risk</b><span>{prediction.recommendation}</span>{prediction.alternate_route && <span><Route size={13} /> {prediction.alternate_route.bypass_name} available</span>}</div>}{error && <p className="inline-error">{error}</p>}</aside>}
    <div className="map-legend"><span><i className="legend-safe" /> Safe</span><span><i className="legend-risk" /> Risky</span><span><i className="legend-blocked" /> Blocked</span><span><i className="legend-vehicle" /> Vehicle</span><span><i className="legend-incident" /> Incident</span></div>
    <MapContainer center={center} zoom={7} minZoom={5} className="leaflet-map" scrollWheelZoom>
      <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution={'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'} />
      <MapHelper focus={focus} onClick={onMapClickCoordinates} />
      {corridors.map((item) => <Polyline key={item.id} positions={item.coordinates} pathOptions={{ color: '#64748b', weight: 3, opacity: .65 }}><Tooltip sticky>{item.name} · {item.status}</Tooltip></Polyline>)}
      {segments.map((item) => <Polyline key={item.id} positions={item.polyline} pathOptions={{ color: color(item.risk_level, item.color), weight: 6, opacity: .9 }}><Tooltip sticky>{item.start_point_name} - {item.end_point_name} · {item.risk_level}</Tooltip></Polyline>)}
      {selectedRoute && <Polyline positions={selectedRoute.waypoints} pathOptions={{ color: '#2563eb', weight: 5, dashArray: '8 8' }}><Tooltip>Selected alternate route</Tooltip></Polyline>}
      {segments.filter((item) => item.alternate_route_polyline?.length).map((item) => <Polyline key={`${item.id}-alternate`} positions={item.alternate_route_polyline!} pathOptions={{ color: '#2563eb', weight: 3, dashArray: '7 7' }} />)}
      {vehiclesVisible && vehicles.map((item) => <Marker key={item.id} position={[item.current_lat, item.current_lng]} icon={vehicleIcon(item)}><Popup><b>{item.plate_number}</b><br />{item.cargo_type}<br />{item.origin_city} → {item.destination_city}<br /><b>{item.status.replace(/_/g, ' ')} · ETA {item.eta_minutes} min</b></Popup></Marker>)}
      {incidentsVisible && incidents.map((item) => <Marker key={item.id} position={[item.latitude, item.longitude]} icon={incidentIcon(item)}><Popup><b>{item.category}</b><br />{item.location_name}<br />{item.description || 'Field report received.'}<br /><small>{item.status} · clearance {item.clearance_eta_hours}h</small><div className="popup-actions">{onUpvoteIncident && <button onClick={() => onUpvoteIncident(item.id)}>Confirm ({item.upvotes})</button>}{onVerifyIncident && item.status === 'REPORTED' && <button onClick={() => onVerifyIncident(item.id)}>Verify</button>}</div></Popup></Marker>)}
      {weatherVisible && weather.map((item) => <Marker key={item.location} position={[item.lat, item.lng]}><Popup><b>{item.location}</b><br />{item.weather_condition}<br />Rainfall: {item.precipitation_mm} mm</Popup></Marker>)}
    </MapContainer>
  </div>;
};
