import React from 'react';
import { BellRing, Clock3, MapPin, RefreshCw, Truck } from 'lucide-react';
import { Alert, AnalyticsSummary, Corridor, Incident, RouteOption, Segment, Vehicle, WeatherData } from '../../types';
import { KpiCards } from './KpiCards';
import { LiveMap } from '../map/LiveMap';
interface Props { corridors: Corridor[]; segments?: Segment[]; vehicles: Vehicle[]; incidents: Incident[]; alerts: Alert[]; weather: WeatherData[]; analytics?: AnalyticsSummary | null; selectedRoute: RouteOption | null; onMapClickCoordinates: (lat: number, lng: number) => void; onUpvoteIncident: (id: string) => void; onVerifyIncident: (id: string) => void; onTriggerReroute?: (id: string) => void; onTriggerDisruption?: (id: string, type: 'landslide' | 'flood' | 'blocked-road') => void; onTriggerLandslideSimulation?: () => void; isSimulating?: boolean; onDismissAlert?: (id: string) => void; onRefresh?: () => void; }
const when = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Now' : date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); };
const alertTone = (value: string) => value === 'CRITICAL' ? 'badge-critical' : value === 'DANGER' ? 'badge-danger' : value === 'WARNING' ? 'badge-warning' : 'badge-info';
const fleetTone = (value: string) => value === 'EMERGENCY_HALT' ? 'badge-critical' : ['REROUTING', 'CAUTION_SLOW', 'DELAYED'].includes(value) ? 'badge-warning' : 'badge-safe';
export const LogisticsDashboardView: React.FC<Props> = ({ corridors, segments, vehicles, incidents, alerts, weather, selectedRoute, onMapClickCoordinates, onUpvoteIncident, onVerifyIncident, onDismissAlert, onRefresh }) => <div className="dashboard-page">
  <div className="page-heading"><div><p className="eyebrow">North Eastern Region · live operations</p><h1>Logistics command center</h1><span>Monitor road accessibility, moving freight and emerging disruptions in one view.</span></div><button className="outline-button" onClick={onRefresh}><RefreshCw size={15} /> Refresh data</button></div>
  <KpiCards vehicles={vehicles} corridors={corridors} alerts={alerts} />
  <div className="command-grid"><section className="map-card"><div className="card-header"><div><h2>Live logistics map</h2><p>Road risk, vehicles and field incidents across the NER</p></div><span className="live-indicator"><i /> Live</span></div><LiveMap compact corridors={corridors} segments={segments} vehicles={vehicles} incidents={incidents} weather={weather} selectedRoute={selectedRoute} onMapClickCoordinates={onMapClickCoordinates} onUpvoteIncident={onUpvoteIncident} onVerifyIncident={onVerifyIncident} onRefresh={onRefresh} /></section>
  <aside className="operations-panel"><section className="info-section"><div className="info-header"><div><BellRing size={17} /><h2>Live alerts</h2></div><span>{alerts.length}</span></div><div className="compact-list">{alerts.length ? alerts.slice(0, 4).map((item) => <article className="alert-row" key={item.id}><span className={`status-badge ${alertTone(item.severity)}`}>{item.severity}</span><div><b>{item.title}</b><p>{item.message}</p><small><MapPin size={11} /> {item.alert_type.replace(/_/g, ' ')} · {when(item.created_at)}</small></div>{onDismissAlert && <button className="icon-button" aria-label="Dismiss alert" onClick={() => onDismissAlert(item.id)}>×</button>}</article>) : <div className="empty-state">No active alerts. The monitored network is clear.</div>}</div></section>
  <section className="info-section vehicle-section"><div className="info-header"><div><Truck size={17} /><h2>Active vehicles</h2></div><span>{vehicles.length}</span></div><div className="compact-list">{vehicles.length ? vehicles.slice(0, 5).map((item) => <article className="vehicle-row" key={item.id}><div><div className="row-title"><b>{item.plate_number}</b><span className={`status-badge ${fleetTone(item.status)}`}>{item.status.replace(/_/g, ' ')}</span></div><p>{item.cargo_type} · {item.destination_city}</p><small><Clock3 size={11} /> ETA {item.eta_minutes ?? '—'} min</small></div></article>) : <div className="empty-state">No vehicle telemetry is available right now.</div>}</div></section></aside></div>
  </div>;
